# Generated by Django 3.1.4 on 2021-02-10 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_service', '0004_auto_20210210_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='YandexCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_number', models.CharField(blank=True, max_length=20)),
                ('count_visits', models.CharField(blank=True, max_length=20)),
                ('count_hits', models.CharField(blank=True, max_length=20)),
                ('count_views', models.CharField(blank=True, max_length=20)),
                ('total_goals', models.CharField(blank=True, max_length=5)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.domaindata')),
            ],
        ),
        migrations.CreateModel(
            name='YandexGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_number', models.CharField(max_length=20)),
                ('goal_name', models.CharField(max_length=100)),
                ('counter_goal', models.CharField(max_length=20)),
                ('counter_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.yandexcounter')),
            ],
        ),
    ]
