# Generated by Django 3.1.4 on 2021-01-06 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingData',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('expiration_date', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DomainData',
            fields=[
                ('url', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ya_counter_number', models.CharField(blank=True, max_length=20)),
                ('expiration_date', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=20)),
                ('ssh', models.BooleanField(default=False)),
                ('hosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.hostingdata')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
