# Generated by Django 3.1.4 on 2020-12-31 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostingData',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DomainData',
            fields=[
                ('url', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ya_counter_number', models.CharField(blank=True, max_length=20)),
                ('expiration_date', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=20)),
                ('hosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_service.hostingdata')),
            ],
        ),
    ]
