# Generated by Django 3.1.4 on 2021-01-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0002_yandexcounter_yandexgoals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaindata',
            name='ya_counter_number',
        ),
    ]
