# Generated by Django 3.1.4 on 2021-02-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0003_remove_domaindata_ya_counter_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yandexgoals',
            name='counter_number',
        ),
        migrations.DeleteModel(
            name='YandexCounter',
        ),
        migrations.DeleteModel(
            name='YandexGoals',
        ),
    ]
