# Generated by Django 3.1.4 on 2021-02-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0004_auto_20210210_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaindata',
            name='username',
        ),
        migrations.RemoveField(
            model_name='hostingdata',
            name='username',
        ),
    ]
