# Generated by Django 3.1.4 on 2020-12-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteData',
            fields=[
                ('url', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ya_counter_number', models.CharField(blank=True, max_length=20)),
                ('expiration_date', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
